### PR TITLE
8.1. Creating a 2D "Metroidvania" Game - Enemy Sprites and Movement

### PR DESCRIPTION
**Pull request by omalleygeorgie**
# Description

This pull request aims to create a tutorial for Creating a 2D "Metroidvania" Game - Enemy Sprites and Movement.

## Introduction

This tutorial involves creating enemy sprites for the 2D "Metroidvania" Game, and implementing animation and movement.

## Contents

- Enemy Sprite Creation, Animation and Movement
- Generating Multiple Enemy Sprites
- Adding Random Movement
- Putting It All Together

## Conclusion

This tutorial continues on from tutorial 7 in the "Metroidvania" series and builds upon the code provided. The tutorial includes code snippets, explanations and the entire code required for this task, along with the necessary resoures.

## Type of Change

- [x] I have added a new tutorial markdown document in the Metroidvania series folder.
- [x] The necessary images for the tutorial are also included.

# Checklist

Please make sure you have completed the following before merging this pull request:

- [x] My submission follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My tutorial is based on an approved tutorial proposal
- [x] I have requested a review from seniors on the Pull Request

### CODE REVIEW

**Comment by omalleygeorgie** [comment]
[8.2. Creating a 2D "Metroidvania" Game - Combat Mechanics](https://trello.com/c/UxMapiaB/389-82-creating-a-2d-metroidvania-game-combat-mechanics)

**Comment by omalleygeorgie** [comment]
[8.1. Creating a 2D "Metroidvania" Game - Enemy Sprites and Movement](https://trello.com/c/nYKJl586/127-81-creating-a-2d-metroidvania-game-enemy-sprites-and-movement)

**Review by omckeon — CHANGES_REQUESTED** [review]
There are a few areas (min path, max path etc) that have various "magic numbers". It would be good to use some constants, or explain why these undefined numbers were used and what they represent.

**Comment by omckeon** [comment]
Closing this PR so that you can make a new PR without the extra files for the Sprite animation tutorial.

**Pull request closed without merging**
