### PR TITLE
Short Tutorial using MouseX/Y in a basic Game - Starter Code Only

### PR DESCRIPTION
**Pull request by CastielM**
# Description

Starter code in C# for a [Mouse X/Y Tutorial](https://programmers.guide/book/part-1-instructions/3-control-flow/4-activities/#flicking-ball-game) tutorial. Includes a variation of the game (called "Volley") as a concept for the tutorial.

# How Has This Been Tested?

Compiled and run with dotnet.

## Additional Notes

Task on hold as requested, this pull request reflects what was completed so far.

### CODE REVIEW

**Comment by CastielM** [comment]
[Short Tutorial using MouseX/Y in a basic Game](https://trello.com/c/Kxvt1pGL/455-short-tutorial-using-mousex-y-in-a-basic-game)

**Comment by CastielM** [comment]
[Short Tutorial using MouseX/Y in a basic Game](https://trello.com/c/Kxvt1pGL/455-short-tutorial-using-mousex-y-in-a-basic-game)

**Comment by CastielM** [comment]
[Short Tutorial using MouseX/Y in a basic Game](https://trello.com/c/Kxvt1pGL/455-short-tutorial-using-mousex-y-in-a-basic-game)

**Review by omckeon — APPROVED** [review]
These are great starter code files.

**Pull request merged**
