### PR TITLE
Sprite Animation Tutorial

### PR DESCRIPTION
**Pull request by omalleygeorgie**
# Description

This pull request aims to create a tutorial for Sprite Animation.

## Introduction

This tutorial involves creating a character sprite and implementing animations for player movement. This tutorial will build upon the Using Animations tutorial, which covers sprite sheets, image cells and animation scripts.

## Contents

- Sprite Sheets
- Animation Script File
- Defining Animations
- Creating Identifiers
- Implementing Animations in C++
- Handling Animations
- Putting It All Together

## Conclusion

This tutorial provides enough detail for a beginner to implement sprite animations. The tutorial includes code snippets, explanations and the entire code required for this task, along with the necessary resoures.

## Type of Change

- [x] I have added a new Sprite Animation folder in Tutorials.
- [x] This includes the tutorial markdown document and image needed for the tutorial.

# Checklist

Please make sure you have completed the following before merging this pull request:

- [x] My submission follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My tutorial is based on an approved tutorial proposal
- [x] I have requested a review from seniors on the Pull Request

### CODE REVIEW

**Comment by omalleygeorgie** [comment]
[Sprite Animation - Tutorial](https://trello.com/c/DixUnQ3s/246-sprite-animation-tutorial)

**Review by omckeon — APPROVED** [review]
Much nicer formatting for beginner coders :) Nice work

**Review by omckeon — CHANGES_REQUESTED** [review]
I have now done a more thorough review of the Sprite Animation Tutorial and have noticed that the code is not actually using any sprites, just bitmaps.
Update this so that you are using the "sprite" data type (and so that it isn't quite so similar to the existing animations tutorial).

**Comment by omckeon** [comment]
Closing this PR so that you can make a new PR with just the Sprite Animation tutorial (without the 8.1 Enemy sprites tutorial)

**Pull request closed without merging**
