### PR TITLE
Creating a 2D "Metroidvania" Game - Camera Movement, Parallax, and Depth

### PR DESCRIPTION
**Pull request by NateXuan**
# Description

This pull request aims to create a tutorial file of 2D "Metroidvania" Game - Camera Movement, Parallax and Depth.

## Introduction
In this tutorial, we will delve into implementing camera movement and parallax scrolling in a 2D "Metroidvania" style game using the SplashKit library. These features are crucial for creating a dynamic and immersive game environment.

## Camera Movement: Lazy Character Movement
- **Concept**: Implement a camera that follows the character with a delay, allowing smooth movement within the screen center before scrolling.
- **Implementation**: Use SplashKit's **center_camera_on** function, tracking the character's position and updating the camera's focus based on the character's movement.

## Parallax Scrolling for Depth
- **Concept**: Create a depth illusion in a 2D scene by moving background layers at different speeds relative to the camera.
- **Implementation**: Set up multiple background layers with varying **parallax_speed** values. Adjust the position of each layer in response to camera movement, rendering them in order from farthest to nearest for a dynamic visual effect.

## Conclusion
Both techniques enhance the game's visual appeal and immersion, with lazy character movement providing smooth gameplay, and parallax scrolling adding depth to the game's environment. Detailed code examples and explanations in the tutorial guide the implementation process using SplashKit.

## Type of Change
- [x]  I have created a new tutorial file in tutorial folder
- [x]  Adding gif and video examples and codes to demonstrate how to implent the feature

# Checklist

Please make sure you have completed the following before merging this pull request:

- [x]  My submission follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  My tutorial is based on an approved tutorial proposal
- [x]  I have requested a review from seniors on the Pull Request

### CODE REVIEW

**Comment by NateXuan** [comment]
[7. Creating a 2D "Metroidvania" Game - Camera Movement, Parallax and Depth](https://trello.com/c/XxKEdTvw/126-7-creating-a-2d-metroidvania-game-camera-movement-parallax-and-depth)

**Comment by NateXuan** [comment]
[2. Creating a 2D "Metroidvania" Game - Project Structure and Initialization](https://trello.com/c/ceMXpNqB/120-2-creating-a-2d-metroidvania-game-project-structure-and-initialization)

**Comment by NateXuan** [comment]
[7. Creating a 2D "Metroidvania" Game - Camera Movement, Parallax and Depth](https://trello.com/c/XxKEdTvw/126-7-creating-a-2d-metroidvania-game-camera-movement-parallax-and-depth)

**Comment by omckeon** [comment]
@NateXuan It seems you have committed changes to too many files. Update the PR to just include the changes for the 1 file.

**Pull request closed without merging**
