### PR TITLE
Create tutorials for Cmake and Sprite Layering Tutorial

### PR DESCRIPTION
**Pull request by MangoS9**
# Description

This pull request is a submission for adding two tutorials to SplashKit-tutorial repository. The tutorial covers the topics "Getting Started With Sprite Layering In Splashkit - Tutorial" and "Building the SplashKit Core Library with CMake - Tutorial".

## Changes Made
- added two tutorial folders name "Cmake Tutorial" and "Sprite Layering Tutorial (C++)"

# How Has This Been Tested?

## Testing Checklist:

- [x] Prettier
- [x] Vale

# Checklist

Please make sure you have completed the following before merging this pull request:

- [x] My submission follows the style guidelines of this project
- [x] My submission is based on the relevant template in `Instructions and Templates/`
- [x] My tutorial is based on an approved tutorial proposal
- [x] I have requested a review from Seniors on the Pull Request

### CODE REVIEW

**Comment by MangoS9** [comment]
[Building the SplashKit Core Library with CMake - Tutorial](https://trello.com/c/p3ZPxrCM/114-building-the-splashkit-core-library-with-cmake-tutorial)

**Comment by MangoS9** [comment]
[Getting Started With Sprite Layering In Splashkit - Tutorial](https://trello.com/c/8wrvLxAY/115-getting-started-with-sprite-layering-in-splashkit-tutorial)

**Comment by MangoS9** [comment]
[Getting Started With Sprite Layering In Splashkit - Tutorial](https://trello.com/c/8wrvLxAY/115-getting-started-with-sprite-layering-in-splashkit-tutorial)

**Comment by MangoS9** [comment]
[Getting Started With Sprite Layering In Splashkit - Tutorial](https://trello.com/c/8wrvLxAY/115-getting-started-with-sprite-layering-in-splashkit-tutorial)

**Review by DaGoblin — APPROVED** [review]
The series looks good effort, actually helps me a bit with cmake as I have no real clue about it at the moment.

**Pull request merged**
