### PR TITLE
Car race tutorial

### PR DESCRIPTION
**Pull request by KhushiLaddi08**
_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

This pull request aims to _describe the purpose of the pull request_.

## Changes Made

_List the changes that have been made_

-

# How Has This Been Tested?

## Testing Checklist:

- [ ] Prettier
- [ ] Vale

# Checklist

Please make sure you have completed the following before merging this pull request:

- [ ] My submission follows the style guidelines of this project
- [ ] My submission is based on the relevant template in _`Instructions and Templates/`_
- [ ] My tutorial is based on an approved tutorial proposal
- [ ] I have requested a review from _..._ on the Pull Request

## Additional Notes

_Provide any additional context or notes about the changes made in this pull request._

## Related Issues

_If this pull request is related to any existing issues, mention them here._

### CODE REVIEW

**Comment by KhushiLaddi08** [comment]
[Car-Race-Tutorial 1](https://trello.com/c/kcTd4z5L/550-car-race-tutorial-1)

**Comment by KhushiLaddi08** [comment]
[Updated files Tutorial](https://trello.com/c/8n8jlfUI/591-updated-files-tutorial)

**Comment by KhushiLaddi08** [comment]
[Updated files Tutorial](https://trello.com/c/8n8jlfUI/591-updated-files-tutorial)

**Review by omckeon — CHANGES_REQUESTED** [review]
These files are looking much better, just need a few improvements:

- Update Step 1 to use the current SplashKit compiling commands (see: https://programmers.guide/book/part-2-organised-code/1-starting-cpp/1-concepts/1-0-building-cpp/#compile-and-run).
- Install the markdownlint VS Code extension to improve the formatting.
- Fix up the indentation issues with the code snippets in some files.
- Add more context about how the program files are created (which files should have which code snippets etc), and where the user will add the code snippets to their own file as they are following along.
- You could also include an image with a structure chart of the final game code. And maybe even a final wrap up page that includes the code in each file.

**Review by omckeon — CHANGES_REQUESTED** [review]
This PR should just have the tutorial files - no game code. Delete the 'car-race' and 'car-race-updated' files and commit those changes and that should remove them from this PR.

**Pull request closed without merging**
