### PR TITLE
Project structure and initialization

### PR DESCRIPTION
**Pull request by NateXuan**
# Description

This pull request aims to create a tutorial of 2D "Metroidvania" Game - Project Structure and Initialization.

## Project Structure
- **Essential Directories**: Organize your project into directories for source code, resources, libraries, build configurations, and documentation.
- **Code and Assets**: Maintain code in .cpp/.h files and assets like images, sounds, and fonts in a separate assets directory.
- **External Dependencies**: Store external libraries or frameworks like SplashKit in a designated library directory.

## SplashKit Project Setup
- **New Project Creation**: Use SplashKit commands to generate a new project, which includes essential directories and files.
- **Directory Setup**: Create src for source code, Resources for assets, and lib for third-party libraries.

## Game Initialization
- **Creating the Game Window**: Open a game window with a specific size and title.
- **Loading Assets**: Load game assets like sprites and music.
- **Initializing Game Variables**: Set up important variables like player health, score, and game state.
- **Game Loop**: Implement the game loop for updating game states and rendering graphics.

## Conclusion
A well-structured project and initialization set the stage for further development, including character design, level creation, and game mechanics.

## Type of Change
- [x] I have created a new tutorial file in tutorial folder
- [x]  Adding screenshot examples and codes to demonstrate how to implent the feature

# Checklist

Please make sure you have completed the following before merging this pull request:

- [x]  My submission follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  My tutorial is based on an approved tutorial proposal
- [x]  I have requested a review from seniors on the Pull Request

### CODE REVIEW

**Comment by NateXuan** [comment]
[2. Creating a 2D "Metroidvania" Game - Project Structure and Initialization](https://trello.com/c/ceMXpNqB/120-2-creating-a-2d-metroidvania-game-project-structure-and-initialization)

**Review by omckeon — CHANGES_REQUESTED** [review]
In "Code and Assets Directories":
- Would be good to mention "Resources" as this is what it is called in SplashKit, rather than Assets.

In "Library and External Dependencies":
- Typo for SplashKit (missing p).
- Would be good to mention that it is a folder called 'lib' in SplashKit.

In "Configuration and Build Scripts":
- Which language creates a "builds" folder in a SplashKit project?
- More detail needed about configuration files - and make it specific to SplashKit.

In "Setting Up Your Project":
- Step 1: More detail needed about changing the directory to a folder before using mkdir.
- Step 2: You need to include instructions about using `skm resources' to create the resource folders that SplashKit uses. And the lib folder should already have been created. 

Other areas:
- Line 51 should be using ```cpp like other lines.
- There is no "update_game" or "draw_game" procedures shown, so either show the code for these, or show the code without these and then mention that these procedures would be used later.
- You need to add a "Putting it all together" section that has the complete code in a block.

**Review by omckeon — CHANGES_REQUESTED** [review]
In "Configuration and Build Scripts": The more common configuration files would be the files in the .vscode hidden folder so you could discuss this instead of the sentence "Explain how to configure SplashKit-specific settings here." (which looks like the tutorial hasn't been finished).

For Resources, mention that 'skm resources' is a terminal command run in the base folder of the project.

Also, you still need to include a final code snippet at the end that includes *ALL* of the code that would be put in the program.cpp file.

**Review by omckeon — APPROVED** [review]
Still missing the last step of "Putting it all together" with ALL of the code, and the game loop code's indentation could be improved, but this is okay for now.

**Pull request merged**
