### PR TITLE
SplashKit Mouse Functionality Guide

### PR DESCRIPTION
**Pull request by AmosSaji**
# Description

This pull request explains the mouse functionality, as a tutorial.

## Changes Made

_List the changes that have been made_

-

# How Has This Been Tested?

## Testing Checklist:

- [ ] Prettier
- [ ] Vale

# Checklist

Please make sure you have completed the following before merging this pull request:

- [ ] My submission follows the style guidelines of this project
- [ ] My submission is based on the relevant template in _`Instructions and Templates/`_
- [ ] My tutorial is based on an approved tutorial proposal
- [ ] I have requested a review from _..._ on the Pull Request

## Additional Notes

_Provide any additional context or notes about the changes made in this pull request._

## Related Issues

_If this pull request is related to any existing issues, mention them here._

### CODE REVIEW

**Comment by AmosSaji** [comment]
[tutorial/guide on the "Mouse" functionality in SplashKit](https://trello.com/c/wmZTmfWA/614-tutorial-guide-on-the-mouse-functionality-in-splashkit)

**Review by omckeon — CHANGES_REQUESTED** [review]
Make sure this proposal is different to the existing tutorial on the splashkit.io site.

And you need to add the final example code to this file using the fenced code blocks.

It seems that some aspects of the Tutorial Template are missing. Make sure you have included all the headings/information requested in that template.

**Comment by AmosSaji** [comment]
> Make sure this proposal is different to the existing tutorial on the splashkit.io site.
> 
> And you need to add the final example code to this file using the fenced code blocks.
> 
> It seems that some aspects of the Tutorial Template are missing. Make sure you have included all the headings/information requested in that template.

Hi Olivia,
I have made the changes as you said. And it is a bit more different than the before one. Please check it out and provide me with your feedback.

**Comment by omckeon** [comment]
Updated Tutorial didn't improve on the existing tutorial, and was too similar.

**Pull request closed without merging**
